# Generated by Django 4.2.6 on 2023-10-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemPage', '0002_submission_delete_problem_delete_testcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_file',
            field=models.FileField(null=True, upload_to='source_codes/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
