# Generated by Django 4.2.6 on 2023-10-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemPage', '0003_submission_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c++', 'cpp'), ('python', 'Python'), ('java', 'Java')], max_length=50),
        ),
    ]
