# Generated by Django 4.2.6 on 2023-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemPage', '0007_testcaseresult_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseresult',
            name='user_output',
            field=models.TextField(default=''),
        ),
    ]
