# Generated by Django 4.2.5 on 2023-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogPage", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="children_comment",
            field=models.ManyToManyField(to="blogPage.integer"),
        ),
    ]
