# Generated by Django 4.2.5 on 2023-11-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogPage", "0003_integer_comment_children_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="children_comment",),
        migrations.DeleteModel(name="Integer",),
    ]
