# Generated by Django 4.2.6 on 2023-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_id', models.IntegerField()),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
            ],
            options={
                'db_table': 'testcases',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('statement', models.TextField()),
                ('input_description', models.TextField(blank=True, null=True)),
                ('output_description', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('testcases', models.ManyToManyField(to='addProblem.testcase')),
            ],
            options={
                'db_table': 'problems',
            },
        ),
    ]
