# Generated by Django 4.2.6 on 2023-10-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProblem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
