# Generated by Django 4.2.6 on 2023-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProblem', '0002_testcase_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tc_shown_id',
            field=models.IntegerField(default=-1),
        ),
    ]
