# Generated by Django 4.2.5 on 2023-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_customuser_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
