# Generated by Django 4.0.4 on 2023-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/blank-profile-picture.png', null=True, upload_to='profile_image/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='university_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
